# Generated by Django 2.0.3 on 2019-07-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190702_0229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
